Repository Kusitms-28th-MeetUp-C/Server, pull requests merged in 2023-10, with the labels that each got.

#2 [init]:global 프로젝트 초기세팅
  .github/PULL_REQUEST_TEMPLATE.md
  MainService/.gitignore
  MainService/build.gradle
  MainService/gradle/wrapper/gradle-wrapper.jar
  MainService/gradle/wrapper/gradle-wrapper.properties
  MainService/gradlew
  MainService/gradlew.bat
  MainService/settings.gradle
  MainService/src/main/java/com/kusitms/mainservice/MainServiceApplication.java
  MainService/src/main/java/com/kusitms/mainservice/global/common/HealthCheckApiController.java
  MainService/src/main/java/com/kusitms/mainservice/global/common/SuccessCode.java
  MainService/src/main/java/com/kusitms/mainservice/global/common/SuccessResponse.java
  MainService/src/main/java/com/kusitms/mainservice/global/common/TimeConverter.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/CustomP6spySqlFormatter.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/P6spyConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/dto/ErrorBaseResponse.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/exception/BusinessException.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/exception/ConflictException.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/exception/EntityNotFoundException.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/exception/ForbiddenException.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/exception/InvalidValueException.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/exception/UnauthorizedException.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/handler/GlobalExceptionHandler.java
  MainService/src/test/java/com/kusitms/mainservice/MainServiceApplicationTests.java
  SocketService/.gitignore
  SocketService/build.gradle
  SocketService/gradle/wrapper/gradle-wrapper.jar
  SocketService/gradle/wrapper/gradle-wrapper.properties
  SocketService/gradlew
  SocketService/gradlew.bat
  SocketService/settings.gradle
  SocketService/src/main/java/com/kusitms/socketservice/SocketServiceApplication.java
  SocketService/src/test/java/com/kusitms/socketservice/SocketServiceApplicationTests.java
Labels: init, feat

#4 [feat]:Global 서비스별 CI/CD 구현
  .github/workflows/main-service-ci.yml
  .github/workflows/main-service-cicd.yml
  .github/workflows/socket-service-ci.yml
  .github/workflows/socket-service-cicd.yml
  MainService/Dockerfile
  MainService/docker-compose.yml
  SocketService/Dockerfile
  SocketService/docker-compose.yml
Labels: feat

#5 [feat]:Global #3 deploy.sh 구현
  scripts/deploy.sh
Labels: feat

#7 [fix]:Global #6 workflow 오타 수정
  .github/workflows/main-service-cicd.yml
  .github/workflows/socket-service-cicd.yml
Labels: fix

#8 [fix]:Global #6 scripts 오타 수정
  scripts/deploy.sh
Labels: fix

#9 [fix]:Global #6 workflow 오타 수정
  .github/workflows/socket-service-cicd.yml
Labels: fix

#11 [feat]:Main #10 구글 로그인 API
  .idea/.gitignore
  .idea/Server.iml
  .idea/dbnavigator.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  MainService/build.gradle
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/GoogleOauthToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/OauthController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/GoogleUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/GoogleUserRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/GoogleOauth.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/OauthService.java
Labels: feat

#19 [refactor] Main #18 구글로그인+JWT 수정
  MainService/build.gradle
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/GoogleOauthToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/OauthController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/GoogleUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/OAuthLoginResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/GoogleUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/OAuthToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/GoogleUserRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/UserRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/security/jwt/JwtTokenProvider.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/security/jwt/TokenInfo.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/GoogleOauth.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/OAuthService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/OauthService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/UserService.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/RestTemplateConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
Labels: refactor

#22 [feat]:Main 소셜로그인+jwt+security
  MainService/build.gradle
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/GoogleOauthToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/OauthController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/GoogleUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/OAuthLoginResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/GoogleUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/OAuthToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/GoogleUserRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/UserRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/security/jwt/JwtTokenProvider.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/security/jwt/TokenInfo.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/GoogleOauth.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/OAuthService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/OauthService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/UserService.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/RestTemplateConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
Labels: feat

#23 [refactor]Main #21 소셜로그인+jwt+security 코드정리
  MainService/build.gradle
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/GoogleUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/KakaoUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/OAuthToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/security/jwt/JwtTokenProvider.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/OAuthService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/UserService.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/SecurityConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/JwtAccessDeniedHandler.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/JwtAuthenticationEntryPoint.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/JwtAuthenticationFilter.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/JwtTokenProvider.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/entity/TokenInfo.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/exception/EmptyTokenException.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/exception/InvalidTokenException.java
Labels: refactor

#20 [feat]:Socket Socket 구축
  .idea/.gitignore
  .idea/Server.iml
  .idea/dbnavigator.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  SocketService/.gitignore
  SocketService/build.gradle
  SocketService/src/main/java/com/kusitms/socketservice/common/AuthenticationInterceptor.java
  SocketService/src/main/java/com/kusitms/socketservice/common/JwtProvider.java
  SocketService/src/main/java/com/kusitms/socketservice/config/RedisConfig.java
  SocketService/src/main/java/com/kusitms/socketservice/config/SocketConfig.java
  SocketService/src/main/java/com/kusitms/socketservice/config/SocketSecurityConfig.java
  SocketService/src/main/java/com/kusitms/socketservice/config/WebConfig.java
  SocketService/src/main/java/com/kusitms/socketservice/config/auth/ExceptionHandlerFilter.java
  SocketService/src/main/java/com/kusitms/socketservice/config/auth/JwtAuthenticationEntryPoint.java
  SocketService/src/main/java/com/kusitms/socketservice/config/auth/JwtAuthenticationFilter.java
  SocketService/src/main/java/com/kusitms/socketservice/config/auth/SecurityConfig.java
  SocketService/src/main/java/com/kusitms/socketservice/config/auth/UserAuthentication.java
  SocketService/src/main/java/com/kusitms/socketservice/controller/MessageController.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/MeetingRoom.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/MessageType.java
  SocketService/src/main/java/com/kusitms/socketservice/dto/request/MessageRequestDto.java
  SocketService/src/main/java/com/kusitms/socketservice/dto/response/MessageResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/error/ErrorCode.java
  SocketService/src/main/java/com/kusitms/socketservice/error/dto/ErrorBaseResponse.java
  SocketService/src/main/java/com/kusitms/socketservice/error/handler/MessageErrorHandler.java
  SocketService/src/main/java/com/kusitms/socketservice/error/httpException/BusinessException.java
  SocketService/src/main/java/com/kusitms/socketservice/error/httpException/InvalidValueException.java
  SocketService/src/main/java/com/kusitms/socketservice/error/httpException/UnauthorizedException.java
  SocketService/src/main/java/com/kusitms/socketservice/error/socketException/BusinessException.java
  SocketService/src/main/java/com/kusitms/socketservice/error/socketException/EntityNotFoundException.java
  SocketService/src/main/java/com/kusitms/socketservice/error/socketException/UnauthorizedException.java
  SocketService/src/main/java/com/kusitms/socketservice/repository/MeetingRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/sevice/MessageService.java
  SocketService/src/main/java/com/kusitms/socketservice/sevice/RedisSubscriber.java
Labels: feat, chore

#27 [refactor]:Main security 최적화
  MainService/build.gradle
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/PlatformUserInfo.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/RestTemplateProvider.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/google/GoogleAuthProvider.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/google/GoogleToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/google/GoogleUserInfo.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/kakao/KakaoAuthProvider.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/kakao/KakaoToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/kakao/KakaoUserInfo.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/Platform.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/RefreshToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/OAuthLoginResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/request/UserSignInRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/request/UserSignUpRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/UserAuthResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/GoogleUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/KakaoUser.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/oauth/OAuthToken.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/RefreshTokenRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/UserRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/AuthService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/OAuthService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/UserService.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/CustomP6spySqlFormatter.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/JpaConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/P6spyConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/RestTemplateConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/auth/ExceptionHandlerFilter.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/auth/JwtAuthenticationEntryPoint.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/auth/JwtAuthenticationFilter.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/auth/JwtProvider.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/auth/TokenInfo.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/auth/UserAuthentication.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/auth/UserId.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/auth/UserIdArgumentResolver.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/SecurityConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/JwtAccessDeniedHandler.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/JwtAuthenticationEntryPoint.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/JwtAuthenticationFilter.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/JwtTokenProvider.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/entity/TokenInfo.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/exception/EmptyTokenException.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/security/jwt/exception/InvalidTokenException.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/exception/InternalServerException.java
Labels: feat, chore, refactor
