Repository Kusitms-28th-MeetUp-C/Server, pull requests merged in 2023-11, with the labels that each got.

#29 [feat]:Main 템플릿 불러오기 엔티티 생성
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/MongoDBTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/MySQLTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Rating.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Reviewer.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateMaker.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateReview.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/TemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/MongoDBRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/MySQLRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/RestTemplateProvider.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/google/GoogleUserInfo.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
Labels: feat

#30 [feat]:Main 유저 로드맵 및 템플릿 관리 domain 구현
  MainService/build.gradle
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/Roadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapDetail.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/UserRoadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/BaseRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/UserRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/UserRoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/MongoDBTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Reviewer.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Template.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateMaker.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateReview.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/MongoDBRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateContentRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/AuthService.java
Labels: feat, fix

#32 [feat]:Main 나의 회의록 template 조회 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/Roadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapDetail.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapDownload.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RelatedRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapTitleResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/UserRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapDownloadRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/UserRoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/CustomTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Template.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateDownload.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/BaseTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/OriginalTemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/RelatedTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateTitleResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/UserBaseTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateContentRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateDownloadRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateUserService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/Team.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/TeamSpace.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
Labels: feat, fix

#34 [feat]:Main 나의 회의록 관리 팀 생성 및 수정 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapDownload.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/BaseRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapDownloadRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapUserService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateUserService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/Team.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/TeamSpace.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/TeamSpaceType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/TeamType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/request/TeamRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/request/TeamRoadmapRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/request/TeamSpaceRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/request/UpdateTeamRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/TeamResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/TeamSpaceResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/TeamRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/TeamService.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
Labels: feat

#38 [feat]:Main 팀 로드맵 상세 조회 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/CustomRoadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/Roadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/BaseRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/CustomRoadmapDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/CustomRoadmapSpaceDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/controller/TeamController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/dto/response/TeamRoadmapDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamRoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/BaseCustomTemplateResponseDto.java
Labels: feat

#41 [feat]:Main 나의 회의록 관리 overview 팀 전체 조회 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/team/controller/TeamController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/dto/response/TeamListElementsResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/dto/response/TeamListResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/repository/TeamRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
Labels: feat

#40 [feat]:Main 템플릿 탐색 api구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/dto/response/TeamTitleResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/repository/TeamRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/CustomTemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Template.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateData.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateReview.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/GetTeamForSaveTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/RatingResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/ReviewContentResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/SaveTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/SearchBaseTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/SearchTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailUserResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/ReviewerRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateContentRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateDownloadRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/CustomTemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/OAuthToken.java
  MainService/src/test/java/com/kusitms/mainservice/MainServiceApplicationTests.java
Labels: feat

#45 [feat]:Main 나의 회의록-회의록 자세히 보기 api 제작
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/CustomRoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/dto/response/TeamSpaceResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/repository/TeamRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamRoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/CustomTemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/BaseCustomTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/CustomTemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDownloadDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/CustomTemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateContentRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/CustomTemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
Labels: feat

#47 [feat]:Main 원본데이터 보기 및 리뷰 작성 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/Roadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/dto/response/TeamSpaceResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/repository/TeamRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/CustomTemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/CustomTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Rating.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Reviewer.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Template.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateReview.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/request/TemplateReviewRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/CustomTemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/OriginalTemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/OriginalTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDownloadDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateTitleResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/ReviewerRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateDownloadRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateReviewRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/MakerResponseDto.java
Labels: feat

#48 [refactor]:Main 템플릿 검색, 템플릿 상세보기 api 정리 (고쳐야 할 것들 있긴함)
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapTitleResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Template.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateDownload.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/SaveTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/CustomTemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/test/java/com/kusitms/mainservice/MainServiceApplicationTests.java
Labels: refactor

#50 [feat]:Main 로드맵 탐색 및 상세내용 보기 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/request/SearchRoadmapRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailInfoResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/SearchBaseRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/SearchRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/CustomRoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapSpaceRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/DetailUserResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
Labels: feat

#52 [chore]:Main cors config 추가
  MainService/src/main/java/com/kusitms/mainservice/global/config/WebConfig.java
Labels: chore

#53 [refactor]:Main template, roadmap 탐색 api 변경
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailInfoResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapDownloadRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Template.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/request/SearchTemplateRequsetDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/SearchBaseTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/ReviewerRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateDownloadRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/AuthService.java
Labels: refactor

#64 [feat]:Main #63 article 불러오기 api 구현
  MainService/build.gradle
  MainService/src/main/java/com/kusitms/mainservice/domain/article/controller/ArticleController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/article/domain/Article.java
  MainService/src/main/java/com/kusitms/mainservice/domain/article/dto/response/ArticleResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/article/repository/ArticleRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/article/service/ArticleService.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/StorageConfig.java
Labels: feat

#67 [feat]:Main #64 mypage api 구현 및 코드 정리
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/Roadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/BaseRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailInfoResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailIntro.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateContentListResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailConnectRoadmapDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailIntroBaseResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailIntroResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/AuthService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/UserService.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
  MainService/src/main/java/com/kusitms/mainservice/global/infra/mypage/controller/MyPageController.java
  MainService/src/main/java/com/kusitms/mainservice/global/infra/mypage/domain/SharedType.java
  MainService/src/main/java/com/kusitms/mainservice/global/infra/mypage/dto/MyPageResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/global/infra/mypage/dto/MyPageUserResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/global/infra/mypage/dto/MySharedContentDto.java
  MainService/src/main/java/com/kusitms/mainservice/global/infra/mypage/service/MyPageService.java
Labels: feat, refactor

#70 [fix]:Socket 채팅 서비스 안정화
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/controller/ChatController.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/Chat.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/ChatContent.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/request/ChatMessageRequestDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatMessageElementResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatMessageResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/SendMessageResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/repository/ChatRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/RedisSubscriber.java
  SocketService/src/main/java/com/kusitms/socketservice/global/common/JwtProvider.java
Labels: fix

#71 [refactor]:Socket 채팅 서비스 코드 정리
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/Chat.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/ChatContent.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/repository/ChatRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
Labels: refactor

#74 [ refactore]:Main 코드 정리
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/controller/MyPageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/domain/SharedType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/MyPageResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/MyPageUserResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/MySharedContentDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/service/MyPageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/UserService.java
Labels: refactor

#78 [feat]:Main 로그아웃 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/AuthService.java
Labels: feat

#80 [feat]:Main 코드정리
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Template.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/request/TemplateSharingRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailIntroResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/global/common/BaseTimeEntity.java
Labels: feat

#82 [fix]:Main api 연동 오류
  MainService/src/main/java/com/kusitms/mainservice/global/config/CorsConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
Labels: feat

#84 [fix]:Main api 로드맵 type 추가
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/CustomRoadmapDetailResponseDto.java
Labels: fix

#85 [feat]:Main roadmap 완료 버튼 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/CustomRoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/CustomRoadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/CustomRoadmapSpace.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/CustomRoadmapService.java
Labels: feat

#86 [refactor]:Main 코드 정리
  MainService/src/main/java/com/kusitms/mainservice/domain/team/controller/TeamController.java
Labels: refactor

#88 [feat]:Main 템플릿 상세보기 UserType 추가
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/UserType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/DetailUserResponseDto.java
Labels: feat

#92 [fix]:Main patch cors 문제 해결
  MainService/src/main/java/com/kusitms/mainservice/global/config/CorsConfig.java
Labels: fix

#93 [fix]:Main patch cors 문제 해결
  MainService/src/main/java/com/kusitms/mainservice/domain/team/controller/TeamController.java
Labels: fix

#95 [fix]:Main team 정보 수정 api 로직 변경
  MainService/src/main/java/com/kusitms/mainservice/domain/team/controller/TeamController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
Labels: fix

#97 [fix]:Main 팀생성 api 오류
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
Labels: fix

#98 [feat]:Main #89 mypage 정보 수정 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/controller/MyPageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/response/MyPageResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/response/MyPageUserResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/response/MySharedContentDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/resquest/ModifyUserProfileRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/service/MyPageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/repository/UserRepository.java
  MainService/src/main/java/com/kusitms/mainservice/global/S3Service.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/StorageConfig.java
Labels: feat

#102 [feat]:Main #101 mypage sharedtype별 데이터 불러오기 api구현
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/controller/MyPageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/domain/SharedType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/resquest/MySharedContentRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/service/MyPageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/Roadmap.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapSpace.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/request/RoadmapSharingRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/request/StepDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/RoadmapDetailIntro.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/CustomRoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/UserAuthResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
Labels: feat

#103 [fix]:Socket 나의 회의록 검색 api 수정
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/controller/SearchController.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/RoadmapType.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/SearchCustomStep.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/SearchCustomTemplate.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/SearchResultType.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/SearchType.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/SearchUserTemplate.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/SubSearchType.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/dto/request/SearchRequestDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/dto/response/SearchResultElementResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/repository/SearchCustomRoadmapRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/repository/SearchCustomStepRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/repository/SearchCustomTemplateRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/repository/SearchRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/repository/SearchRepositoryImpl.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/service/SearchService.java
Labels: fix

#107 [fix]:Socket 회의록 탐색 api response 수정
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/controller/SearchController.java
  SocketService/src/main/java/com/kusitms/socketservice/global/common/MessageSuccessCode.java
Labels: fix

#108 [feat]:Main 템플릿 미리보기 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/team/controller/TeamController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/dto/response/TeamTitleElementResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/dto/response/TeamTitleListResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: feat

#109 [feat]:Main template 미리 보기 api controller 임시 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
Labels: fix

#112 [feat]:Main #101 다른 사람 프로필 보기 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/article/controller/ArticleController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/controller/MyPageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/response/MyPageResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/response/NotMyPageRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/response/NotMyPageTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/resquest/ModifyUserProfileRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/resquest/NotMyPageRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/service/MyPageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/SearchBaseRoadmapResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/SaveTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/SearchBaseTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
Labels: feat

#116 [feat]:Main template 사용하기 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/CustomTemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/request/TemplateTeamRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
Labels: feat

#118 [feat]:Main #117 로드맵 생성 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapSpace.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/domain/RoadmapTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/request/RoadmapSharingRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/request/StepDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/CreateTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: feat

#120 [refactor]:Main #117 코드정리
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/service/MyPageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/CustomRoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/CustomRoadmapDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/CustomRoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/TemplateDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/test/java/com/kusitms/mainservice/MainServiceApplicationTests.java
Labels: refactor

#121 [fix]:Socket 채팅 리스트 조회 api response 수정
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/Chat.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/ChatUser.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/User.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/UserType.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatMessageListResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatMessageResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatUserResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/repository/UserRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
  SocketService/src/main/java/com/kusitms/socketservice/global/error/ErrorCode.java
Labels: feat, fix

#123 [fix]:Main 팀 정보 상세보기 & 팀 정보 전체 조회 api response dto 수정
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/CustomRoadmapDetailResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamRoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/UserType.java
Labels: feat

#125 [refactor]:Main #117 roadmapManageService 코드 정리
  MainService/src/main/java/com/kusitms/mainservice/domain/article/controller/ArticleController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/response/CreateTemplateResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: fix, refactor

#126 [fix]:Main team space 수정 api
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
Labels: fix

#128 [fix]:Socket 채팅방 생성관련 오류 수정
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/ChatUser.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
Labels: fix

#129 [fix]:Socket 채팅방 리스트 response dto 응답값에 유저 정보 추가
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatMessageListResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/UserChatResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
Labels: fix

#130 [fix]:Socket 채팅방 리스트 response dto 응답값에 유저 타입 추가
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/UserChatResponseDto.java
Labels: fix

#133 [feat]:Main #131 템플릿 삭제 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: feat

#135 [fix]:Socket search 빈 string 버그 해결
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/controller/SearchController.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/repository/SearchRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/repository/SearchRepositoryImpl.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/service/SearchService.java
Labels: feat, fix

#138 [fix]:Main #136 cors 오류 해결
  MainService/src/main/java/com/kusitms/mainservice/global/config/CorsConfig.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/WebConfig.java
Labels: fix

#141 [fix]:Main #136 dto sessionId 필드 추가
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/response/MyPageUserResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/DetailUserResponseDto.java
Labels: fix

#145 [fix]:Main 회원가입 api 로직 수정
  MainService/src/main/java/com/kusitms/mainservice/domain/mypage/dto/response/MyPageUserResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/UserType.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/request/UserSignUpRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/DetailUserResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/UserAuthResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/AuthService.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
Labels: fix

#147 [fix]:Socket 채팅 세부정보확인 api에서 유저 정보가 바뀌는 오류 해결
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/UserType.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatUserResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/UserChatResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
  SocketService/src/main/java/com/kusitms/socketservice/global/error/ErrorCode.java
Labels: fix

#149 [fix]:Main 로그인 회원가입에 따른 whiteList 오타 수정
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
Labels: fix

#151 [fix]: Main custom_roadmap_repository 오류 수정
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/CustomRoadmapRepository.java
  MainService/src/test/java/com/kusitms/mainservice/MainServiceApplicationTests.java
Labels: fix

#152 [fix]: Main template, roadmap탐색하기 생성된 날짜에 따른 정렬
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/RoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/repository/TemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
Labels: fix

#154 [fix]:Main 로그인 중복 처리 로직 에러 수정
  MainService/src/main/java/com/kusitms/mainservice/domain/user/domain/User.java
Labels: fix

#158 [fix]:Main 로그인 jwt token null 에러 처리
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/AuthService.java
Labels: fix

#160 [fix]:Main api 연동 오류 해결
  .github/workflows/main-service-cicd.yml
Labels: fix

#161 [fix]:Main api 연동 오류
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamRoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/SearchUserTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/mongoRepository/SearchUserTemplateRepository.java
Labels: fix

#162 [fix]:Socket #159 sessionId 생성 후 채팅 생성 로직 수정
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/controller/ChatController.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/ChatUser.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/User.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/request/ChatMessageListRequestDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/request/ChatMessageRequestDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatMessageResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatUserResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/UserChatResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/repository/UserRepository.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/RedisSubscriber.java
Labels: fix

#163 [fix]:Socket sessionId string으로 변환 후 search 로직 수정
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/controller/ChatController.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/controller/SearchController.java
  SocketService/src/main/java/com/kusitms/socketservice/global/config/SocketConfig.java
  SocketService/src/main/java/com/kusitms/socketservice/global/config/auth/UserId.java
  SocketService/src/main/java/com/kusitms/socketservice/global/config/auth/UserIdArgumentResolver.java
Labels: fix

#165 [fix]:Socket 비어있는 채팅으로 인해 발생하는 오류 해결
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
Labels: fix

#166 [fix]:Socket 온보딩으로 부터 받은 유저 이름 response에 적용
  MainService/src/main/java/com/kusitms/mainservice/domain/user/controller/UserController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/UserSignUpResponseDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/service/AuthService.java
Labels: fix

#167 [feat]: Main Template 수정하기 API구현
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/CustomTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/request/UpdateTemplateRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/dto/response/UserAuthResponseDto.java
  MainService/src/test/java/com/kusitms/mainservice/MainServiceApplicationTests.java
Labels: feat, fix

#168 [fix]: Main Template 저장하기 API 수정
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/CustomTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/request/UpdateTemplateRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: fix

#169 [fix]: Main Template 수정하기 API 수정
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/CustomTemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: fix

#171 [fix]: Main Template 수정하기 API 수정
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: fix

#172 [feat]: Main Template 팀에 배정하기전 스텝 불러오기
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/CustomRoadmapStepDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/CustomRoadmapSpaceRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: feat

#173 [fix]:Global search template 로직 수정
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamRoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/CustomTemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/SearchUserTemplate.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/Template.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateDownload.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateReview.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/dto/request/TemplateTeamRequestDto.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/mongoRepository/SearchUserTemplateRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
  MainService/src/main/java/com/kusitms/mainservice/global/error/ErrorCode.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/SearchUserTemplate.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/dto/response/SearchResultElementResponseDto.java
Labels: fix

#174 [fix]:Socket 채팅 유저 기록 시간순으로 정렬
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
Labels: fix

#175 [feat]: Main Template 팀에 배정하기 api 구현
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/controller/RoadmapManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/dto/response/CustomRoadmapTitleAndStep.java
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/team/repository/TeamRepository.java
Labels: feat

#176 [fix]:Main custom template content 생성 id 중복 오류 해결
  MainService/src/main/java/com/kusitms/mainservice/domain/team/service/TeamRoadmapService.java
Labels: fix

#178 [fix]:Main mongo db unique id 조회 오류 해결
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/repository/CustomRoadmapRepository.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/CustomTemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/domain/TemplateContent.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
Labels: fix

#180 [fix]: Main 템플릿, 로드맵 탐색하기 whiteList추가 및 코드정리
  MainService/src/main/java/com/kusitms/mainservice/domain/roadmap/service/RoadmapService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/controller/TemplateManageController.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateManageService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/template/service/TemplateService.java
  MainService/src/main/java/com/kusitms/mainservice/domain/user/auth/RestTemplateProvider.java
  MainService/src/main/java/com/kusitms/mainservice/global/config/SecurityConfig.java
Labels: fix

#188 [fix]:Socker 코드정리
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/domain/TemplateType.java
Labels: fix

#190 [refactor]:Main 코드 정렬 및 불필요 메서드 제거
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/domain/ChatUser.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatMessageResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/dto/response/ChatUserResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/chat/service/ChatService.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/controller/SearchController.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/dto/response/SearchResultElementResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/dto/response/SearchResultResponseDto.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/repository/SearchRepositoryImpl.java
  SocketService/src/main/java/com/kusitms/socketservice/domain/search/service/SearchService.java
  SocketService/src/main/java/com/kusitms/socketservice/global/common/JwtProvider.java
  SocketService/src/main/java/com/kusitms/socketservice/global/config/MongoDbConfig.java
  SocketService/src/main/java/com/kusitms/socketservice/global/error/ErrorCode.java
  SocketService/src/main/java/com/kusitms/socketservice/global/error/httpException/InvalidValueException.java
  SocketService/src/main/java/com/kusitms/socketservice/global/error/httpException/UnauthorizedException.java
Labels: refactor
